name: Lighthouse Report

on: 
  schedule:
    - cron: "30 12 * * *"
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lighthouse-workflow:
    uses: mikesprague/reusable-workflows/.github/workflows/lighthouse.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    with:
      url: 'https://birdle.app'

